### ISSUE TITLE
Fatal Error when enabling plugin -- "TextAttributeKey(name:'ASM_MNEMONIC' [...]) was already registered [...]"

### ISSUE THREAD

**Issue by spyoungtech** [mike42/6502-assembly-intellij#2]
Thank you for producing this plugin. I find it really helpful.

I enabled the plugin (after disabling it) and got a fatal error/stack trace. I don't have much more context to add. The project was pretty much brand new and no code was written.

Everything seems to be OK though after I just closed the stack trace window and I can't reproduce the error again by taking the same steps.

OS: MacOS Catalina
IDE: CLion 2021.2.3 
Plugin version: 1.2

Other plugins installed:
- [rust](https://plugins.jetbrains.com/plugin/8182-rust)
- [toml](https://plugins.jetbrains.com/plugin/8195-toml)

I hope this helps you improve the plugin. If someone knows how to reliably reproduce, would be happy to test fixes.

Cheers!

Relevant part of stack trace:

```
java.lang.IllegalStateException: TextAttributeKey(name:'ASM_MNEMONIC', fallbackAttributeKey:'DEFAULT_INSTANCE_METHOD')  was already registered with the other fallback attribute key: DEFAULT_KEYWORD
	at com.intellij.openapi.editor.colors.TextAttributesKey.mergeKeys(TextAttributesKey.java:220)
	at com.intellij.openapi.editor.colors.TextAttributesKey.lambda$getOrCreate$4(TextAttributesKey.java:206)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1932)
	at com.intellij.openapi.editor.colors.TextAttributesKey.getOrCreate(TextAttributesKey.java:206)
	at com.intellij.openapi.editor.colors.TextAttributesKey.createTextAttributesKey(TextAttributesKey.java:193)
	at org.ca65.AsmSyntaxHighlighter.<clinit>(AsmSyntaxHighlighter.java:19)
	at org.ca65.AsmSyntaxHighlighterFactory.getSyntaxHighlighter(AsmSyntaxHighlighterFactory.java:15)
	at com.intellij.openapi.fileTypes.SyntaxHighlighterFactory.getSyntaxHighlighter(SyntaxHighlighterFactory.java:25)
	at com.intellij.openapi.fileTypes.LanguageFileTypeHighlighterProvider.create(LanguageFileTypeHighlighterProvider.java:15)
	at jdk.internal.reflect.GeneratedMethodAccessor207.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.openapi.util.KeyedExtensionFactory.getByKey(KeyedExtensionFactory.java:77)
        [...]
```

**Comment by mike42** [comment]
I haven't seen this particular error, but I was able to replicate a more general issue of the plugin not working correctly on CLion. It appears to conflict with CLion's built-in modern assembly language support, which cannot be switched off.

I don't know if it's possible to fix this, so as of version 1.3, I've updated the `plugin.xml` to list the incompatibility.

![image](https://user-images.githubusercontent.com/2080552/151686559-efa9cdd5-4037-4357-a90e-e4f5543acadd.png)

Older versions of CLion may still show old versions of the plugin, but on a new-ish installation, the plugin will no longer appear in the marketplace.

![image](https://user-images.githubusercontent.com/2080552/151686676-9fa60b8c-6b45-4da5-a52b-c2726bf6eeba.png)
